Shaz b1
auraside/hone-game-configs pull request #10
Opened 2024-04-25 08:59 UTC by shaz2327

Created Config files for Naraka Bladepoint, Path of Exile and Warframe

2024-04-26 13:37 UTC, JonathahWasTaken requested changes
dialogue_sound_volume2 max 7?

select_object need names too map, so either:

"AntiAliasingMethod": {
  "key": "anti_aliasing",
  "type": "select_object",
  "options": {
    "Off": "Off",
    "Low": "Low",
    "High": "High",
  }
}

or use select_array

2024-04-26 13:38 UTC, JonathahWasTaken approved these changes

2024-04-26 13:38 UTC, JonathahWasTaken approved these changes

2024-04-26 13:40 UTC, JonathahWasTaken approved these changes

2024-04-29 06:30 UTC, shaz2327 commented
> dialogue_sound_volume2 max 7?

The Music and master volume max value was 100 but for dialogue volume it was 700. Do we still use 0 to 1 in that case?

>
> select_object need names too map, so either:
> 
> "AntiAliasingMethod": { "key": "anti_aliasing", "type": "select_object", "options": { "Off": "Off", "Low": "Low", "High": "High", } }
> 
> or use select_array

Replaced select_object with select_array

2024-04-30 03:16 UTC, JonathahWasTaken approved these changes

2024-04-30 03:17 UTC, JonathahWasTaken approved these changes

2024-04-30 03:18 UTC, JonathahWasTaken commented
> > dialogue_sound_volume2 max 7?
> 
> The Music and master volume max value was 100 but for dialogue volume it was 700. Do we still use 0 to 1 in that case?
> 
> > select_object need names too map, so either:
> > "AntiAliasingMethod": { "key": "anti_aliasing", "type": "select_object", "options": { "Off": "Off", "Low": "Low", "High": "High", } }
> > or use select_array
> 
> Replaced select_object with select_array

No need to replace it to 1, if its how it is in-game that's how it should be. Good job!

2024-04-30 03:18 UTC, merged